version: "3.3"

services:
  mysql:
    image: mysql:latest
    networks:
      - backend
    env_file:
      - ./scripts/.env
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    #args:
    #  - tags="swagger"

    # for deployment, comment out the build section and use the image below
    #image: planvx/aweme:latest
    # Load environment variables from .env file
    env_file:
      - ./scripts/.env
    volumes:
      # Use configs folder for configuration files
      - ./configs:/app/configs
    expose:
      - "80"
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  backend:
