release: true
mysql:
  dsn: $MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_ADDRESS)/$MYSQL_DATABASE?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true

jwt:
  secret: $JWT_SECRET
  ttl: 259200 # 3 days, 3 * 24 * 60 * 60
  whitelist:

api:
  prefix: /v1
  address: 0.0.0.0:80

s3: # alternatively, you can use minio
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  endpoint: ${S3_ENDPOINT}

redis:
  address: [$REDIS_ADDRESS] # support multiple redis address
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}

otel:
  endpoint: ${OTEL_ENDPOINT}
  service: aweme
  version: v0.4.1
  environment: production
