release: true
mysql:
  address: $MYSQL_ADDRESS
  username: $MYSQL_USER
  password: $MYSQL_PASSWORD
  database: $MYSQL_DATABASE

jwt:
  secret: $JWT_SECRET
  ttl: 259200 # 3 days, 3 * 24 * 60 * 60
  whitelist:

api:
  prefix: /v1

s3:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}
  endpoint: ${S3_ENDPOINT}
  partition: ${S3_PARTITION}
