// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PlanVX",
            "url": "https://github.com/PlanVX"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://github.com/PlanVX/aweme/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comment/action/": {
            "post": {
                "description": "评论操作",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动接口"
                ],
                "summary": "评论操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "1-发布评论，2-删除评论",
                        "name": "action_type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "要删除的评论id，在action_type=2的时候使用",
                        "name": "comment_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户填写的评论内容，在action_type=1的时候使用",
                        "name": "comment_text",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CommentActionResp"
                        }
                    }
                }
            }
        },
        "/comment/list/": {
            "get": {
                "description": "评论列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动接口"
                ],
                "summary": "评论列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CommentListResp"
                        }
                    }
                }
            }
        },
        "/favorite/action/": {
            "post": {
                "description": "赞操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动接口"
                ],
                "summary": "赞操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "1-点赞，2-取消点赞",
                        "name": "action_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.FavoriteActionResp"
                        }
                    }
                }
            }
        },
        "/favorite/list/": {
            "get": {
                "description": "点赞列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "互动接口"
                ],
                "summary": "点赞列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.FavoriteListResp"
                        }
                    }
                }
            }
        },
        "/feed/": {
            "get": {
                "description": "获取视频列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "获取视频列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间",
                        "name": "latest_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "登录状态则有",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.FeedResp"
                        }
                    }
                }
            }
        },
        "/message/action/": {
            "post": {
                "description": "消息操作",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "消息操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "1-发送消息",
                        "name": "action_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "消息内容",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "对方用户id",
                        "name": "to_user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.MessageActionResp"
                        }
                    }
                }
            }
        },
        "/message/chat/": {
            "get": {
                "description": "聊天记录",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "聊天记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对方用户id",
                        "name": "to_user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.MessageListResp"
                        }
                    }
                }
            }
        },
        "/publish/action/": {
            "post": {
                "description": "上传视频",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "上传视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Data",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UploadResp"
                        }
                    }
                }
            }
        },
        "/publish/list/": {
            "get": {
                "description": "获取视频列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "获取视频列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.PublishListResp"
                        }
                    }
                }
            }
        },
        "/relation/action/": {
            "post": {
                "description": "关系操作",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "关系操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "1-关注，2-取消关注",
                        "name": "action_type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "对方用户 id",
                        "name": "to_user_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户鉴权 token",
                        "name": "token",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RelationActionResp"
                        }
                    }
                }
            }
        },
        "/relation/follow/list/": {
            "get": {
                "description": "用户关注列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "用户关注列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RelationFollowListResp"
                        }
                    }
                }
            }
        },
        "/relation/follower/list/": {
            "get": {
                "description": "用户粉丝列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "用户粉丝列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RelationFollowerListResp"
                        }
                    }
                }
            }
        },
        "/relation/friend/list/": {
            "get": {
                "description": "用户好友列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交接口"
                ],
                "summary": "用户好友列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户鉴权token",
                        "name": "token",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.RelationFriendListResp"
                        }
                    }
                }
            }
        },
        "/user/": {
            "get": {
                "description": "用户信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UserInfoResp"
                        }
                    }
                }
            }
        },
        "/user/login/": {
            "post": {
                "description": "用户登陆",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "maxLength": 16,
                        "minLength": 6,
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 16,
                        "minLength": 1,
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UserResp"
                        }
                    }
                }
            }
        },
        "/user/register/": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基础接口"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "maxLength": 16,
                        "minLength": 6,
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 16,
                        "minLength": 1,
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UserResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "评论内容",
                    "type": "string"
                },
                "create_date": {
                    "description": "评论发布日期，格式 mm-dd",
                    "type": "string"
                },
                "id": {
                    "description": "评论id",
                    "type": "integer"
                },
                "user": {
                    "description": "评论用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.User"
                        }
                    ]
                }
            }
        },
        "types.CommentActionResp": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "评论成功返回评论内容，不需要重新拉取整个列表",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Comment"
                        }
                    ]
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.CommentListResp": {
            "type": "object",
            "properties": {
                "comment_list": {
                    "description": "评论列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Comment"
                    }
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.FavoriteActionResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.FavoriteListResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "video_list": {
                    "description": "用户点赞视频列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Video"
                    }
                }
            }
        },
        "types.FeedResp": {
            "type": "object",
            "properties": {
                "next_time": {
                    "description": "本次返回的视频中，发布最早的时间，作为下次请求时的latest_time",
                    "type": "integer"
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "video_list": {
                    "description": "视频列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Video"
                    }
                }
            }
        },
        "types.FriendUserResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "用户头像 URL",
                    "type": "string"
                },
                "background_image": {
                    "description": "用户个人页顶部大图",
                    "type": "string"
                },
                "favorite_count": {
                    "description": "点赞数量",
                    "type": "integer"
                },
                "follow_count": {
                    "description": "关注总数",
                    "type": "integer"
                },
                "follower_count": {
                    "description": "粉丝总数",
                    "type": "integer"
                },
                "id": {
                    "description": "用户id",
                    "type": "integer"
                },
                "is_follow": {
                    "description": "true-已关注，false-未关注",
                    "type": "boolean"
                },
                "message": {
                    "description": "和该好友的最新聊天消息",
                    "type": "string"
                },
                "msg_type": {
                    "description": "message消息的类型，0 =\u003e 当前请求用户接收的消息， 1 =\u003e 当前请求用户发送的消息",
                    "type": "integer"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string"
                },
                "signature": {
                    "description": "个人简介",
                    "type": "string"
                },
                "total_favorited": {
                    "description": "获赞数量",
                    "type": "integer"
                },
                "work_count": {
                    "description": "作品数量",
                    "type": "integer"
                }
            }
        },
        "types.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "消息内容",
                    "type": "string"
                },
                "create_time": {
                    "description": "消息创建时间",
                    "type": "string"
                },
                "from_user_id": {
                    "description": "该消息发送者的id",
                    "type": "integer"
                },
                "id": {
                    "description": "消息id",
                    "type": "integer"
                },
                "to_user_id": {
                    "description": "该消息接收者的id",
                    "type": "integer"
                }
            }
        },
        "types.MessageActionResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.MessageListResp": {
            "type": "object",
            "properties": {
                "message_list": {
                    "description": "消息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Message"
                    }
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.PublishListResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "video_list": {
                    "description": "用户发布的视频列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Video"
                    }
                }
            }
        },
        "types.RelationActionResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.RelationFollowListResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user_list": {
                    "description": "用户信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.User"
                    }
                }
            }
        },
        "types.RelationFollowerListResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user_list": {
                    "description": "用户信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.User"
                    }
                }
            }
        },
        "types.RelationFriendListResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user_list": {
                    "description": "用户信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.FriendUserResp"
                    }
                }
            }
        },
        "types.UploadResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "types.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "用户头像 URL",
                    "type": "string"
                },
                "background_image": {
                    "description": "用户个人页顶部大图",
                    "type": "string"
                },
                "favorite_count": {
                    "description": "点赞数量",
                    "type": "integer"
                },
                "follow_count": {
                    "description": "关注总数",
                    "type": "integer"
                },
                "follower_count": {
                    "description": "粉丝总数",
                    "type": "integer"
                },
                "id": {
                    "description": "用户id",
                    "type": "integer"
                },
                "is_follow": {
                    "description": "true-已关注，false-未关注",
                    "type": "boolean"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string"
                },
                "signature": {
                    "description": "个人简介",
                    "type": "string"
                },
                "total_favorited": {
                    "description": "获赞数量",
                    "type": "integer"
                },
                "work_count": {
                    "description": "作品数量",
                    "type": "integer"
                }
            }
        },
        "types.UserInfoResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.User"
                        }
                    ]
                }
            }
        },
        "types.UserResp": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "token": {
                    "description": "用户鉴权token",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "types.Video": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "视频作者信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.User"
                        }
                    ]
                },
                "comment_count": {
                    "description": "视频的评论总数",
                    "type": "integer"
                },
                "cover_url": {
                    "description": "视频封面地址",
                    "type": "string"
                },
                "favorite_count": {
                    "description": "视频的点赞总数",
                    "type": "integer"
                },
                "id": {
                    "description": "视频唯一标识",
                    "type": "integer"
                },
                "is_favorite": {
                    "description": "true-已点赞，false-未点赞",
                    "type": "boolean"
                },
                "play_url": {
                    "description": "视频播放地址",
                    "type": "string"
                },
                "title": {
                    "description": "视频标题",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "aweme",
	Description:      "aweme api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
