name: "build"
on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Swagger Docs Generation
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g cmd/main.go

      - name: Go Code Test
        run: |
          go mod download
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt

      - name: Go Build
        run: |
          go build  -ldflags="-w -s"  -o  app cmd/main.go