name: "CI"
on:
  push:
    branches:
      - '*'
    tags:
      - ''
  pull_request:
    branches:
      - '*'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Code Generation
        run: |
          MOCKERY=1 sh ./scripts/codegen.sh

      - name: Go Code Test
        run: |
          go mod tidy
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt

      - name: Go Build
        run: |
          go build  -ldflags="-w -s"  -o  app cmd/aweme/main.go

  container:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Code Generation
        run: |
          sh ./scripts/codegen.sh

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/uptrace-apm' && github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./scripts/Dockerfile
          push: ${{ github.ref == 'refs/heads/uptrace-apm' && github.event_name == 'push' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME || 'aweme' }}/aweme:apm